name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.22']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
          cache-dependency-path: "${{ github.workspace }}/go.sum"

      - name: Build
        run: go build -v ./...

      - name: Test
        shell: bash
        run: DB_TEST_PATH=/tmp go test -v -race ./...
